platform :ios, '18.6'
target 'SurpriseApp' do
  use_frameworks!
  pod 'YandexMobileMetrica', '~> 4.5'

  target 'SurpriseAppTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.6'
    end
  end
end
