#!/bin/bash
set -e
mkdir -p /home/getmanova/Surprise/images/photo
mkdir -p /home/getmanova/Surprise/images/transparent

wget -q -O "/home/getmanova/Surprise/images/photo/2.webp" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/2.webp"
wget -q -O "/home/getmanova/Surprise/images/photo/3.webp" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/3.webp"
wget -q -O "/home/getmanova/Surprise/images/photo/6.jpeg" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/6.jpeg"
wget -q -O "/home/getmanova/Surprise/images/photo/9.jpg" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/9.jpg"
wget -q -O "/home/getmanova/Surprise/images/photo/22.webp" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/22.webp"
wget -q -O "/home/getmanova/Surprise/images/photo/23.webp" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/23.webp"
wget -q -O "/home/getmanova/Surprise/images/photo/24.webp" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/24.webp"
wget -q -O "/home/getmanova/Surprise/images/photo/25.webp" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/25.webp"
wget -q -O "/home/getmanova/Surprise/images/photo/27.webp" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/27.webp"
wget -q -O "/home/getmanova/Surprise/images/photo/28.jpg" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/28.jpg"
wget -q -O "/home/getmanova/Surprise/images/photo/30.jpg" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/30.jpg"
wget -q -O "/home/getmanova/Surprise/images/photo/32.jpg" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/32.jpg"
wget -q -O "/home/getmanova/Surprise/images/photo/33.jpg" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/33.jpg"
wget -q -O "/home/getmanova/Surprise/images/photo/35.webp" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/35.webp"
wget -q -O "/home/getmanova/Surprise/images/photo/36.jpg" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/36.jpg"
wget -q -O "/home/getmanova/Surprise/images/photo/37.webp" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/37.webp"
wget -q -O "/home/getmanova/Surprise/images/photo/41.webp" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/41.webp"
wget -q -O "/home/getmanova/Surprise/images/photo/42.webp" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/42.webp"
wget -q -O "/home/getmanova/Surprise/images/photo/44.webp" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/44.webp"
wget -q -O "/home/getmanova/Surprise/images/photo/45.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/45.png"
wget -q -O "/home/getmanova/Surprise/images/photo/50.webp" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/50.webp"
wget -q -O "/home/getmanova/Surprise/images/photo/51.jpg" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/51.jpg"
wget -q -O "/home/getmanova/Surprise/images/photo/53.jpg" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/53.jpg"
wget -q -O "/home/getmanova/Surprise/images/photo/54.webp" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/54.webp"
wget -q -O "/home/getmanova/Surprise/images/photo/59.jpg" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/59.jpg"
wget -q -O "/home/getmanova/Surprise/images/photo/61.webp" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/61.webp"
wget -q -O "/home/getmanova/Surprise/images/photo/62.webp" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/62.webp"
wget -q -O "/home/getmanova/Surprise/images/photo/65.jpg" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/65.jpg"
wget -q -O "/home/getmanova/Surprise/images/photo/67.jpg" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/67.jpg"
wget -q -O "/home/getmanova/Surprise/images/photo/68.jpg" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/68.jpg"
wget -q -O "/home/getmanova/Surprise/images/photo/69.jpg" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/69.jpg"
wget -q -O "/home/getmanova/Surprise/images/photo/70.jpg" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/70.jpg"
wget -q -O "/home/getmanova/Surprise/images/photo/71.webp" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/71.webp"
wget -q -O "/home/getmanova/Surprise/images/photo/72.jpg" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/72.jpg"
wget -q -O "/home/getmanova/Surprise/images/photo/77.webp" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/77.webp"
wget -q -O "/home/getmanova/Surprise/images/photo/78.webp" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/78.webp"
wget -q -O "/home/getmanova/Surprise/images/photo/79.webp" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/photo/79.webp"

wget -q -O "/home/getmanova/Surprise/images/transparent/4.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/4.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/5.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/5.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/7.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/7.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/8.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/8.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/15.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/15.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/18.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/18.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/20.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/20.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/21.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/21.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/26.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/26.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/31.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/31.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/34.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/34.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/38.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/38.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/39.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/39.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/43.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/43.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/46.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/46.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/48.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/48.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/49.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/49.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/52.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/52.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/55.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/55.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/56.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/56.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/58.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/58.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/60.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/60.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/64.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/64.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/66.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/66.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/73.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/73.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/74.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/74.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/75.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/75.png"
wget -q -O "/home/getmanova/Surprise/images/transparent/76.png" "https://btlwrtkddswocsosqrnf.supabase.co/storage/v1/object/public/gifts/transparent/76.png"

echo "Done: $(find /home/getmanova/Surprise/images -type f | wc -l) files downloaded"